create table config_google_sheets(
	id 		int unsigned auto_increment primary key,
	course int unsigned not null,
	key_ varchar(200) not null,
	clientId varchar(200) not null,
	projectId varchar(200) not null,
	authUri varchar(200) not null,
	tokenUri varchar(200) not null,
	authProvider varchar(200) not null,
	clientSecret varchar(200) not null,
	redirectUris varchar(500) not null,
	authUrl varchar(500) null,
	accessToken varchar(200) null,
	expiresIn varchar(200) null,
	scope varchar(200) null,
	tokenType varchar(200) null,
	created varchar(200) null,
	refreshToken varchar(500) null,
	authCode varchar(200) null,
	spreadsheetId varchar(200) null,
	sheetName varchar(200) null,
	isEnabled boolean,	
	periodicityNumber int,
	periodicityTime varchar(25),
	foreign key(course) references course(id) on delete cascade
);
