import os

ROOT_PATH = os.path.dirname(os.path.abspath(__file__))
IMPORTED_FUNCTIONS_FOLDER = os.path.join(ROOT_PATH, "imported-functions")
RULES_PATH = None

COURSE = None
TEST_MODE = False
AUTOSAVE = False

LOG_ID_COL = 0
LOG_USER_COL = 1
LOG_DESCRIPTION_COL = 2
LOG_TYPE_COL = 3
LOG_POST_COL = 4
LOG_DATE_COL = 5
LOG_RATING_COL = 6
LOG_EVALUATOR_COL = 7

AWARD_ID_COL = 0
AWARD_USER_COL = 1
AWARD_COURSE_COL = 2
AWARD_DESCRIPTION_COL = 3
AWARD_TYPE_COL = 4
AWARD_INSTANCE_COL = 5
AWARD_REWARD_COL = 6
AWARD_DATE_COL = 7

SPENDING_ID_COL = 0
SPENDING_USER_COL = 1
SPENDING_COURSE_COL = 2
SPENDING_DESCRIPTION_COL = 3
SPENDING_AMOUNT_COL = 4
SPENDING_DATE_COL = 5

HOST = "127.0.0.1"  # The server's hostname or IP address
PORT = 8004         # The port used by the server
